'use client'

import React, { useState, useEffect } from 'react'

export function ShakespeareDemo() {
  const [generatedText, setGeneratedText] = useState<string>('')
  const [displayText, setDisplayText] = useState<string>('')
  const [isLoading, setIsLoading] = useState(true)
  const [currentSampleStart, setCurrentSampleStart] = useState(0)

  useEffect(() => {
    // Load the Shakespeare text from the file
    fetch('/resources/files/shakespeare.txt')
      .then(response => response.text())
      .then(text => {
        setGeneratedText(text)
        // Take first 1000 characters for display
        const displaySubset = text.substring(0, 1000)
        setDisplayText(displaySubset)
        setCurrentSampleStart(0)
        setIsLoading(false)
      })
      .catch(error => {
        console.error('Error loading Shakespeare text:', error)
        // Fallback text if file doesn't exist or can't be loaded
        const fallbackText = `HAMLET:
To be or not to be, that is the question:
Whether 'tis nobler in the mind to suffer
The slings and arrows of outrageous fortune,
Or to take arms against a sea of troubles,
And by opposing end them? To die: to sleep;
No more; and by a sleep to say we end
The heart-ache and the thousand natural shocks
That flesh is heir to, 'tis a consummation
Devoutly to be wish'd.

CLAUDIUS:
How fares our cousin Hamlet?

HAMLET:
Excellent, i' faith; of the chameleon's dish: I eat
the air, promise-crammed: you cannot feed capons so.

CLAUDIUS:
I have nothing with this answer, Hamlet; these words
are not mine.

HAMLET:
No, nor mine now. My lord, you played once i' the
university, you say?

POLONIUS:
That did I, my lord; and was accounted a good actor.

HAMLET:
What did you enact?

POLONIUS:
I did enact Julius Caesar: I was killed i' the
Capitol; Brutus killed me.

HAMLET:
It was a brute part of him to kill so capital a calf
there. Be the players ready?`
        setGeneratedText(fallbackText)
        setDisplayText(fallbackText)
        setIsLoading(false)
      })
  }, [])

  const formatShakespeareText = (text: string) => {
    const lines = text.split('\n')
    const formattedLines: JSX.Element[] = []
    
    lines.forEach((line, index) => {
      if (line.trim() === '') {
        formattedLines.push(<br key={index} />)
      } else if (line.match(/^[A-Z][A-Z\s]+:/)) {
        // Character name
        formattedLines.push(
          <div key={index} className="font-bold text-amber-300 mt-4 mb-2 text-lg">
            {line}
          </div>
        )
      } else if (line.trim().startsWith('[') && line.trim().endsWith(']')) {
        // Stage direction
        formattedLines.push(
          <div key={index} className="italic text-gray-400 text-sm my-2">
            {line}
          </div>
        )
      } else {
        // Regular dialogue
        formattedLines.push(
          <div key={index} className="text-gray-200 mb-1 leading-relaxed">
            {line}
          </div>
        )
      }
    })
    
    return formattedLines
  }

  const generateNewSample = () => {
    if (generatedText.length <= 1000) return
    
    // Calculate maximum start position to ensure we have at least 1000 characters
    const maxStart = generatedText.length - 1000
    let newStart = Math.floor(Math.random() * maxStart)
    
    // Ensure we don't get the same sample twice in a row
    while (newStart === currentSampleStart && maxStart > 0) {
      newStart = Math.floor(Math.random() * maxStart)
    }
    
    const newSample = generatedText.substring(newStart, newStart + 1000)
    setDisplayText(newSample)
    setCurrentSampleStart(newStart)
  }

  return (
    <div className="my-8 p-6 bg-gradient-to-br from-amber-900 to-orange-900 rounded-xl shadow-lg">
      <h3 className="text-xl font-bold text-white mb-4">Generated Shakespeare Sample</h3>
      
      {isLoading ? (
        <div className="bg-black/30 p-6 rounded-lg">
          <div className="animate-pulse">
            <div className="h-4 bg-gray-600 rounded w-3/4 mb-2"></div>
            <div className="h-4 bg-gray-600 rounded w-1/2 mb-2"></div>
            <div className="h-4 bg-gray-600 rounded w-2/3 mb-2"></div>
            <div className="h-4 bg-gray-600 rounded w-3/4 mb-2"></div>
          </div>
          <p className="text-sm text-gray-400 mt-4">Loading generated text...</p>
        </div>
      ) : (
        <>
          <div className="bg-black/30 p-6 rounded-lg font-mono text-sm overflow-y-auto max-h-96">
            {formatShakespeareText(displayText)}
            {generatedText.length > 1000 && (
              <div className="mt-4 pt-4 border-t border-gray-600">
                <p className="text-sm text-gray-400 italic">
                  ...and much more in the full generation! This is just a sample of the {generatedText.length} characters generated by the model.
                </p>
              </div>
            )}
          </div>
          
          {generatedText.length > 1000 && (
            <div className="mt-4 flex justify-center">
              <button
                onClick={generateNewSample}
                className="px-4 py-2 bg-amber-600 hover:bg-amber-700 text-white rounded-lg font-medium transition-colors duration-200 flex items-center gap-2"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                </svg>
                Generate New Sample
              </button>
            </div>
          )}
        </>
      )}
      
      <div className="mt-4 text-sm text-gray-300">
        <p>
          <strong>Model:</strong> 8-layer transformer with 8 attention heads (37.2M parameters)
        </p>
        <p>
          <strong>Training:</strong> Character-level on tiny-shakespeare dataset
        </p>
        <p>
          <strong>Context:</strong> 256 characters, trained for 5000 iterations
        </p>
      </div>
    </div>
  )
} 